iata_cities = {
    'ACA':'Acapulco',
    'AGU':'Aguascalientes',
    'AMS':'Ámsterdam',
    'ATL':'Atlanta',
    'BJX':'León',
    'BOG':'Bogotá',
    'BZE':'Belice',
    'CDG':'París',
    'CEN':'Ciudad Obregón',
    'CJS':'Ciudad Juárez',
    'CLT':'Charlotte',
    'CME':'Ciudad Del Carmen',
    'CTM':'Chetumal',
    'CUN':'Cancún',
    'CUU':'Chihuahua',
    'CZM':'Cozumel',
    'DFW':'Dallas',
    'GDL':'Guadalajara',
    'GUA':'Ciudad de Guatemala',
    'HAV':'La Habana',
    'HMO':'Hermosillo',
    'HUX':'Huatulco',
    'IAH':'Houston',
    'JFK':'Nueva York',
    'LAX':'Los Ángeles',
    'LIM':'Lima',
    'MAD':'Madrid',
    'MEX':'Ciudad de México',
    'MIA':'Miami',
    'MID':'Merida',
    'MTY':'Monterrey',
    'MZT':'Mazatlan',
    'OAX':'Oaxaca',
    'ORD':'Chicago',
    'PBC':'Puebla',
    'PHL':'Filadelfia',
    'PHX':'Phoenix',
    'PVR':'Puerto Vallarta',
    'PXM':'Puerto Escondido',
    'QRO':'Querétaro',
    'SCL':'Santiago de Chile',
    'SLP':'San Luis Potosí',
    'TAM':'Tampico',
    'TIJ':'Tijuana',
    'TLC':'Toluca',
    'TRC':'Coahuila',
    'VER':'Veracruz',
    'VSA':'Villahermosa',
    'YVR':'Vancouver',
    'YYZ':'Toronto',
    'ZCL':'Zacatecas',
    'ZIH':'Ixtapa/Zihuatenejo',
}